lenra-io/components-api

api/components/overlayEntry.schema.json

feat: OverlayEntry implementation

---

api/components/radio.schema.json
api/defs/materialTapTargetSize.schema.json
api/defs/radioStyle.schema.json
api/defs/visualDensity.schema.json

feat: Radio rework

---

api/components/slider.schema.json

feat: Slider implementation

---

api/components/checkbox.schema.json
api/defs/checkboxStyle.schema.json
api/defs/outlinedBorder.schema.json
api/defs/visualDensity.schema.json

feat: Checkbox rework

---

api/components/slider.schema.json

fix: Fixed bad reference property

---

api/defs/textShadow.schema.json

docs: Fix textShadow title

---

api/components/container.schema.json

docs: Fix Container title

---

api/components/actionable.schema.json

docs: Added doc to actionables listeners

---

api/components/widget.schema.json

This allow to handle widget in apps.

feat: add widget schema

---

api/components/overlayEntry.schema.json

Linked to https://github.com/lenra-io/lenra_ui_runner/issues/137

fix: Fixed overlay

---

api/components/textfield.schema.json
api/defs/boxHeightStyle.schema.json
api/defs/boxWidthStyle.schema.json
api/defs/brightness.schema.json
api/defs/dragStartBehavior.schema.json
api/defs/floatingLabelBehavior.schema.json
api/defs/inputBorder.schema.json
api/defs/inputDecoration.schema.json
api/defs/maxLengthEnforcement.schema.json
api/defs/radius.schema.json
api/defs/strutStyle.schema.json
api/defs/textAlign.schema.json
api/defs/textAlignVertical.schema.json
api/defs/textCapitalization.schema.json
api/defs/textFieldStyle.schema.json
api/defs/textInputAction.schema.json
api/defs/textInputType.schema.json
api/defs/textLeadingDistribution.schema.json
api/defs/toolbarOptions.schema.json

feat: TextField rework

---

api/components/text.schema.json

Closes https://github.com/lenra-io/lenra_ui_runner/issues/142

feat: Add TextAlign property to Text

---

api/query/binaryFunction.schema.json
api/query/contains.schema.json

Closes https://github.com/lenra-io/components-api/issues/109

feat: Add contains to parser

---

api/components/widget.schema.json

fix: Widget title

---

api/components/widget.schema.json

feat: Add coll to the widget

---

.github/workflows/semantic_release.yml
.releaserc.yml

ci: Artifact path was incorrect

---

docs/src/pages/actionable.mdx
docs/src/pages/button.mdx
docs/src/pages/checkbox.mdx
docs/src/pages/container.mdx
docs/src/pages/dropdownButton.mdx
docs/src/pages/flex.mdx
docs/src/pages/flexible.mdx
docs/src/pages/icon.mdx
docs/src/pages/image.mdx
docs/src/pages/menu.mdx
docs/src/pages/menuItem.mdx
docs/src/pages/overlayEntry.mdx
docs/src/pages/radio.mdx
docs/src/pages/slider.mdx
docs/src/pages/stack.mdx
docs/src/pages/statusSticker.mdx
docs/src/pages/text.mdx
docs/src/pages/textfield.mdx
docs/src/pages/toggle.mdx
docs/src/pages/widget.mdx
docs/src/pages/wrap.mdx

docs: Add components documentation

---

docs/src/components/propertyTable.jsx

Fixes #125
Signed-off-by: shiipou <shiishii@nocturlab.fr>

fix: Fix components-api in each defs URL

---

api/components/container.schema.json

Closes https://github.com/lenra-io/components-api/issues/131

feat: Container alignment property

---

api/components/actionable.schema.json

linked to https://github.com/lenra-io/lenra_ui_runner/issues/197

feat: Add submit property to Actionable

---

docs/src/pages/components/form.mdx

Add the form component documentation page.

fix: Add form component page

---

api/defs/radioStyle.schema.json

Linked to https://github.com/lenra-io/lenra_components/issues/105

feat: Radio unselected color

---

api/components/view.schema.json
api/defs/find.schema.json

feat: add view.schema.json

---

api/component.schema.json
api/components/carousel.schema.json
api/defs/carouselOptions.schema.json
api/defs/duration.schema.json
docs/src/pages/components/carousel.mdx

Linked to https://github.com/lenra-io/lenra_ui_runner/pull/219

feat: Carousel

---

docs/src/pages/components/view.mdx

Closes https://github.com/lenra-io/components-api/issues/124

feat: remove manifest
